name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo-a-string
        run: echo "hello from the virtual machine (ubuntu)"
      - name: check-node-version  
        run: node -v
  lets-get-it:
    runs-on: ubuntu-latest
    steps:
      - name: echo-second-string
        run: echo "hello from the second VM"
  echo-hi:
    steps:
      - name: echo-string-hi
        run: echo "hi"
